---
fail_fast: true
default_language_version:
  python: python3
repos:
  - repo: local
    hooks:
      - id: format
        name: Format
        language: system
        entry: npm run format:write
        types: [ts]
      - id: lint
        name: Lint
        language: system
        entry: npm run lint
        types: [ts]
      - id: test
        name: Test
        language: system
        entry: npm run test
        pass_filenames: false
      - id: package
        name: Package
        language: system
        entry: npm run package
        pass_filenames: false
