on: 
  # push:
  pull_request:

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test ReSim Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test ReSim Action with logging
        uses: ./
        with:
          # Only needed for testing (defaults to prod)
          api_endpoint: 'https://api.resim.io/v1/'
          auth0_tenant_url: 'https://resim-dev.us.auth0.com/'
          debug_logging: true
          # Secrets have to be passed in explicitly
          client_id: ${{ secrets.TEST_CLIENT_ID }}
          client_secret: ${{ secrets.TEST_CLIENT_SECRET }}
          # What to do
          resource: batch
          operation: create
          build: 2815ed32-f225-4a92-b8d5-592807a8c475
          experiences: 449d52fc-a328-46b5-800b-1e1f771525fa,34a7fc66-cfae-4af1-a8ba-f0355f64c8aa
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test ReSim Action without logging
        uses: ./
        with:
          api_endpoint: 'https://api.resim.io/v1/'
          auth0_tenant_url: 'https://resim-dev.us.auth0.com/'
          client_id: ${{ secrets.TEST_CLIENT_ID }}
          client_secret: ${{ secrets.TEST_CLIENT_SECRET }}

  